__BASE__: "Base.yaml"

POLICY:
  POLICY_NAME: "GEN_navdp"
  BACKBONE: "concerto_s"
  BACKBONE_PATH: "/dataset/nav-e2e/data_navdp/gen_pretrain/concerto_small.pth"
  STATE_DIM: 3
  MIXTURE_GAUSSIAN_NUM: 3
  ENC_LAYERS: 1
  DEC_LAYERS: 3
  CHUNK_SIZE: 24
  UNCERTAINTY_RANGE: [-10, 10]

TRAIN:
  NUM_ITERATIONS: 50000
  LOG_INTERVAL: 100
  NUM_WORKERS: 4
  SAVE_CHECKPOINT_INTERVAL: 1000
  BATCH_SIZE_PER_GPU: 128
  LR: 0.00001
  LR_BACKBONE: 0.00000
  DECAY_LR_ITER_STEPS: []
  DATA_SAMPLE_MODE: 'random'
  MAX_TOKEN_DROP_RATIO: 0.8

DATA:
  DATASET_DIR: ['/dataset/nav-e2e/data_navdp/NavDPData',]
  MAIN_MODALITY: 'point'  # 'image' or 'point'
  IMG_RESIZE_SHAPE: [320, 240]
  VALID_DEPTH_RANGE: [0.1, 5.0]
  VOXEL_DOWNSAMPLE_VOXEL_SIZE: 0.2